name: run gen code on matlab runner on dispatch from simulink repo
on:
  push

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MLM_LICENSE_TOKEN }} # Defined as a secret in GitHub conf

jobs:
  create-artifact:
    name: Generate source code from simulink models and create artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: feature/model_processing_addition

      - uses: cachix/install-nix-action@v23
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b
          cache: true
          products: |
            Simulink
            Signal_Processing_Toolbox
            Simulink_Coder
            Embedded_Coder
            Phased_Array_System_Toolbox
            Control_System_Toolbox
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Mako
        run: |
          pip install mako
      
      - name: Checkout the HyTech_sim repo
        uses: actions/checkout@v4
        with:
          repository: hytech-racing/HyTech_sim
          token: ${{ secrets.KRISHS_PAT }} 
          path: HyTech_sim
          ref: 'main'

      - name: Run matlab script
        uses: matlab-actions/run-command@v2
        with:
          command: gencode_v2
      
      - name: Generate cpp lib script
        run: |
          mkdir source_code
          python process_simulink_codegen.py source_code

      - name: Create proto lib
        run: | 
          mkdir output_proto
          python json_to_proto.py Tire_Model_Codegen_inport_info.json

      - name: Create cpp lib release artifact
        run: | 
          tar -czvf matlab_math.tar.gz source_code

      - name: Debug
        run: |
          ls

      - run: nix run .#nanopb-runner -- ${{ steps.date.outputs.date }}

      - name: Create proto release artifact
        run: | 
          mkdir -p estimation_msgs_pb_lib
          mv *.pb.* estimation_msgs_pb_lib
          mv estimation_msgs_version.h estimation_msgs_pb_lib
          echo -e "{\n\"name\": \"estimation_msgs_pb_lib\",\n\"version\": \"1.${{ github.run_number }}.0\"\n}" >> estimation_msgs_pb_lib/library.json
          tar -czvf estimation_msgs_pb_lib.tar.gz estimation_msgs_pb_lib

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::CodeGen_$(date +"%Y.%m.%d_%H-%M")"

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            matlab_math.tar.gz
            estimation_msgs_pb_lib.tar.gz
            