name: run gen code on matlab runner on dispatch from simulink repo
on:
  push  # TODO change this after it works to workflow_dispatch

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MLM_LICENSE_TOKEN }} # Defined as a secret in GitHub conf

jobs:
  create-artifact:
    name: Generate source code from simulink models and create artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b
          cache: true
          products: |
            Simulink
            Signal_Processing_Toolbox
            Simulink_Coder
            Embedded_Coder
            Phased_Array_System_Toolbox
            Control_System_Toolbox
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Mako
        run: |
          pip install mako
      
      - name: Checkout the HyTech_sim repo
        uses: actions/checkout@v4
        with:
          repository: hytech-racing/HyTech_sim
          token: ${{ secrets.KRISHS_PAT }}
          path: HyTech_sim
          ref: 'main'

      - name: Debugging
        run: |
          ls

      - name: Run matlab script
        uses: matlab-actions/run-command@v2
        with:
          command: gencode_v2
      
      - name: Run Python script
        run: |
          mkdir source_code
          python process_simulink_codegen.py source_code

      - name: Build artifact
        run: | 
          mkdir build
          tar -czvf mathlab_models.tar.gz source_code build
        
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with: 
          name: dist
          path: build/mathlab_models/
